//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims2HoodDuplicator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims2HoodDuplicator.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belladonna Cove.
        /// </summary>
        public static string Belladonna_Cove {
            get {
                return ResourceManager.GetString("Belladonna Cove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desiderata Valley.
        /// </summary>
        public static string Desiderata_Valley {
            get {
                return ResourceManager.GetString("Desiderata Valley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem copying {0} to your game files..
        /// </summary>
        public static string Error_Copying {
            get {
                return ResourceManager.GetString("Error Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No The Sims 2 installation was detected. Please install The Sims 2 before running this application..
        /// </summary>
        public static string Not_Installed {
            get {
                return ResourceManager.GetString("Not Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasantview.
        /// </summary>
        public static string Pleasantview {
            get {
                return ResourceManager.GetString("Pleasantview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 2 Hood Duplicator.
        /// </summary>
        public static string Program_Name {
            get {
                return ResourceManager.GetString("Program Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverblossom Hills.
        /// </summary>
        public static string Riverblossom_Hills {
            get {
                return ResourceManager.GetString("Riverblossom Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strangetown.
        /// </summary>
        public static string Strangetown {
            get {
                return ResourceManager.GetString("Strangetown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The neighborbood was successfully duplicated as {0}..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veronaville.
        /// </summary>
        public static string Veronaville {
            get {
                return ResourceManager.GetString("Veronaville", resourceCulture);
            }
        }
    }
}
